# See https://ezcv.readthedocs.io for documentation 
name: Jeffrey Chung
theme: dimension
email: Jeffreychungcl@gmail.com
role: DevSecOps Intern | Production Assistant
company: University of Technology Sydney (UTS) | Synergy Effects
biography: |
   Aspiring developer passionate about creating, testing and maintaining tools for pipeline development. Related work experience in the Unity 
   Engine as a Production Assistant at Synergy Effects and using CI/CD and testing frameworks as a DevSecOps Intern at UTS.
   <br>
   <br>
   <br>Itch.io: https://k1ngslayer.itch.io/
examples: true
social:
  github: Jeffrey-Chung 
  linkedin: jeffrey-chung-462448257 