# See https://ezcv.readthedocs.io for documentation
name: Jeffrey Chung
theme: dimension
email: Jeffreychungcl@gmail.com
role: DevSecOps Intern | Production Assistant
company: University of Technology Sydney (UTS) | Synergy Effects
resume: false
biography: |
   Aspiring developer passionate about creating, testing and maintaining tools for pipeline development. Related work experience in the Unity 
   Engine as a Production Assistant at Synergy Effects and using CI/CD and testing frameworks as a DevSecOps Intern at UTS.
examples: true
social:
  github: Jeffrey-Chung # Your username on github 
  linkedin: jeffrey-chung-462448257 #Don't know why it loads instagram instead on linux mint